//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from UCM.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IUCMListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class UCMBaseListener : IUCMListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.object_t"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject_t([NotNull] UCMParser.Object_tContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.object_t"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject_t([NotNull] UCMParser.Object_tContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.array_t"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_t([NotNull] UCMParser.Array_tContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.array_t"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_t([NotNull] UCMParser.Array_tContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveType([NotNull] UCMParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveType([NotNull] UCMParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.complexType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterComplexType([NotNull] UCMParser.ComplexTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.complexType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitComplexType([NotNull] UCMParser.ComplexTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] UCMParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] UCMParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.num"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNum([NotNull] UCMParser.NumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.num"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNum([NotNull] UCMParser.NumContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] UCMParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] UCMParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.augmentedString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAugmentedString([NotNull] UCMParser.AugmentedStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.augmentedString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAugmentedString([NotNull] UCMParser.AugmentedStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.concatanatedString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConcatanatedString([NotNull] UCMParser.ConcatanatedStringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.concatanatedString"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConcatanatedString([NotNull] UCMParser.ConcatanatedStringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] UCMParser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.string"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] UCMParser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.typedId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypedId([NotNull] UCMParser.TypedIdContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.typedId"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypedId([NotNull] UCMParser.TypedIdContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.adapting"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdapting([NotNull] UCMParser.AdaptingContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.adapting"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdapting([NotNull] UCMParser.AdaptingContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject([NotNull] UCMParser.ObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject([NotNull] UCMParser.ObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField([NotNull] UCMParser.FieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField([NotNull] UCMParser.FieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] UCMParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] UCMParser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.evaluaterArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEvaluaterArray([NotNull] UCMParser.EvaluaterArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.evaluaterArray"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEvaluaterArray([NotNull] UCMParser.EvaluaterArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.templateField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateField([NotNull] UCMParser.TemplateFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.templateField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateField([NotNull] UCMParser.TemplateFieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.templateExtention"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateExtention([NotNull] UCMParser.TemplateExtentionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.templateExtention"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateExtention([NotNull] UCMParser.TemplateExtentionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.templateDefenition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateDefenition([NotNull] UCMParser.TemplateDefenitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.templateDefenition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateDefenition([NotNull] UCMParser.TemplateDefenitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.functionCollection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCollection([NotNull] UCMParser.FunctionCollectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.functionCollection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCollection([NotNull] UCMParser.FunctionCollectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethod([NotNull] UCMParser.MethodContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethod([NotNull] UCMParser.MethodContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.functionCollectionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCollectionCall([NotNull] UCMParser.FunctionCollectionCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.functionCollectionCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCollectionCall([NotNull] UCMParser.FunctionCollectionCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodCall([NotNull] UCMParser.MethodCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.methodCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodCall([NotNull] UCMParser.MethodCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] UCMParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] UCMParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.numExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumExpr([NotNull] UCMParser.NumExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.numExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumExpr([NotNull] UCMParser.NumExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.boolExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolExpr([NotNull] UCMParser.BoolExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.boolExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolExpr([NotNull] UCMParser.BoolExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.compExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompExpr([NotNull] UCMParser.CompExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.compExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompExpr([NotNull] UCMParser.CompExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] UCMParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] UCMParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.conditional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional([NotNull] UCMParser.ConditionalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.conditional"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional([NotNull] UCMParser.ConditionalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.whileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileLoop([NotNull] UCMParser.WhileLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.whileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileLoop([NotNull] UCMParser.WhileLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.forLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForLoop([NotNull] UCMParser.ForLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.forLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForLoop([NotNull] UCMParser.ForLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.listConstruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListConstruction([NotNull] UCMParser.ListConstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.listConstruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListConstruction([NotNull] UCMParser.ListConstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.statementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatementList([NotNull] UCMParser.StatementListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.statementList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatementList([NotNull] UCMParser.StatementListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] UCMParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] UCMParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] UCMParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] UCMParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.objectDefenition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectDefenition([NotNull] UCMParser.ObjectDefenitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.objectDefenition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectDefenition([NotNull] UCMParser.ObjectDefenitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.arrayDefenition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayDefenition([NotNull] UCMParser.ArrayDefenitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.arrayDefenition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayDefenition([NotNull] UCMParser.ArrayDefenitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] UCMParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] UCMParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.root"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRoot([NotNull] UCMParser.RootContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.root"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRoot([NotNull] UCMParser.RootContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] UCMParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] UCMParser.StartContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
