//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from UCM.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="UCMParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IUCMListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.object_t"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject_t([NotNull] UCMParser.Object_tContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.object_t"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject_t([NotNull] UCMParser.Object_tContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.array_t"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_t([NotNull] UCMParser.Array_tContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.array_t"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_t([NotNull] UCMParser.Array_tContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimitiveType([NotNull] UCMParser.PrimitiveTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.primitiveType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimitiveType([NotNull] UCMParser.PrimitiveTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.complexType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplexType([NotNull] UCMParser.ComplexTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.complexType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplexType([NotNull] UCMParser.ComplexTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] UCMParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] UCMParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNum([NotNull] UCMParser.NumContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.num"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNum([NotNull] UCMParser.NumContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] UCMParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] UCMParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.augmentedString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAugmentedString([NotNull] UCMParser.AugmentedStringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.augmentedString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAugmentedString([NotNull] UCMParser.AugmentedStringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.concatanatedString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConcatanatedString([NotNull] UCMParser.ConcatanatedStringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.concatanatedString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConcatanatedString([NotNull] UCMParser.ConcatanatedStringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] UCMParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] UCMParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.typedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypedId([NotNull] UCMParser.TypedIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.typedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypedId([NotNull] UCMParser.TypedIdContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.adapting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdapting([NotNull] UCMParser.AdaptingContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.adapting"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdapting([NotNull] UCMParser.AdaptingContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject([NotNull] UCMParser.ObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject([NotNull] UCMParser.ObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] UCMParser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] UCMParser.FieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray([NotNull] UCMParser.ArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray([NotNull] UCMParser.ArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.evaluaterArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEvaluaterArray([NotNull] UCMParser.EvaluaterArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.evaluaterArray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEvaluaterArray([NotNull] UCMParser.EvaluaterArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.templateField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateField([NotNull] UCMParser.TemplateFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.templateField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateField([NotNull] UCMParser.TemplateFieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.templateExtention"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateExtention([NotNull] UCMParser.TemplateExtentionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.templateExtention"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateExtention([NotNull] UCMParser.TemplateExtentionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.templateDefenition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTemplateDefenition([NotNull] UCMParser.TemplateDefenitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.templateDefenition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTemplateDefenition([NotNull] UCMParser.TemplateDefenitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.functionCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCollection([NotNull] UCMParser.FunctionCollectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.functionCollection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCollection([NotNull] UCMParser.FunctionCollectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethod([NotNull] UCMParser.MethodContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.method"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethod([NotNull] UCMParser.MethodContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.functionCollectionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCollectionCall([NotNull] UCMParser.FunctionCollectionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.functionCollectionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCollectionCall([NotNull] UCMParser.FunctionCollectionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMethodCall([NotNull] UCMParser.MethodCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMethodCall([NotNull] UCMParser.MethodCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] UCMParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] UCMParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.numExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumExpr([NotNull] UCMParser.NumExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.numExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumExpr([NotNull] UCMParser.NumExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.boolExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolExpr([NotNull] UCMParser.BoolExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.boolExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolExpr([NotNull] UCMParser.BoolExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.compExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompExpr([NotNull] UCMParser.CompExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.compExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompExpr([NotNull] UCMParser.CompExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] UCMParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] UCMParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.conditional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditional([NotNull] UCMParser.ConditionalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.conditional"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditional([NotNull] UCMParser.ConditionalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileLoop([NotNull] UCMParser.WhileLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileLoop([NotNull] UCMParser.WhileLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForLoop([NotNull] UCMParser.ForLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForLoop([NotNull] UCMParser.ForLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.listConstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterListConstruction([NotNull] UCMParser.ListConstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.listConstruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitListConstruction([NotNull] UCMParser.ListConstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementList([NotNull] UCMParser.StatementListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.statementList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementList([NotNull] UCMParser.StatementListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] UCMParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] UCMParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] UCMParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] UCMParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.objectDefenition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectDefenition([NotNull] UCMParser.ObjectDefenitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.objectDefenition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectDefenition([NotNull] UCMParser.ObjectDefenitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.arrayDefenition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayDefenition([NotNull] UCMParser.ArrayDefenitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.arrayDefenition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayDefenition([NotNull] UCMParser.ArrayDefenitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] UCMParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] UCMParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRoot([NotNull] UCMParser.RootContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.root"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRoot([NotNull] UCMParser.RootContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="UCMParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] UCMParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="UCMParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] UCMParser.StartContext context);
}
